name: Build PancakeOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip wget

      - name: Create .love file
        run: |
          cd $GITHUB_WORKSPACE
          zip -9 -r pancakeos.love . -x '*.git*' '*.github*' '*.vscode*'

      - name: Build Linux tarball
        run: |
          # Create a simple tar.gz containing the .love file and a small launcher script
          mkdir -p pancakeos-linux
          cp pancakeos.love pancakeos-linux/
          printf '#!/bin/sh\nDIR=$(dirname "$0")\nexec love "${DIR}/pancakeos.love"\n' > pancakeos-linux/run.sh
          chmod +x pancakeos-linux/run.sh
          tar -czf PancakeOS-linux.tar.gz -C pancakeos-linux .
          ls -la PancakeOS-linux.tar.gz

      - name: Build Windows .exe and zip
        run: |
          wget https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
          unzip love-11.5-win64.zip -d love-win64
          ls -l love-win64
          if [ -f love-win64/love.exe ]; then
            cat love-win64/love.exe pancakeos.love > PancakeOS.exe
          else
            cat love-win64/*/love.exe pancakeos.love > PancakeOS.exe
          fi
          cp love-win64/**/*.dll . || cp love-win64/*.dll .
          zip -r PancakeOS-windows.zip PancakeOS.exe *.dll

      - name: Build macOS .app
        run: |
          wget https://github.com/love2d/love/releases/download/11.5/love-11.5-macos.zip
          unzip love-11.5-macos.zip -d love-macos
          cp pancakeos.love love-macos/love.app/Contents/Resources/
          mv love-macos/love.app love-macos/PancakeOS.app
          # Optionally update Info.plist here for customizations
          cd love-macos
          zip -r ../PancakeOS-macOS.zip PancakeOS.app
          cd ..



      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PancakeOS-builds
          path: |
            pancakeos.love
            PancakeOS-windows.zip
            PancakeOS-macOS.zip
              PancakeOS-linux.tar.gz

  # release job removed: releasing is handled by .github/workflows/release.yml
